export const environment = {
  production: false,
  stripePublicKey: 'pk_test_51JhGPzEr164QO1Kb8FdmFbmmyAAixxNnftXtvzfwQqun2eToP4OmlZhkjomR9UNiA97TcGuh3IfJsj1BgkLwvcBt00pIFjyExI',
  stripePublicKeyLive:'pk_live_51JhGPzEr164QO1KbD3UXh9LMANe9ItYyBHScGROV4ORdoQ2oiNBvkh7R6FeqtF7KxvZV9n0B2I32eYWwp2q6xEi600mIz5vsuV',
  stripeSecertKey:'sk_test_51JhGPzEr164QO1KbxCKBAuITlwThslOySvbT4tW9KI9NJl4E4GCcfhtnYxmugjwI35aImln3668YNTSCBt1VNTQU00wpjRIjLW',
  apiBaseUrl: 'http://localhost:8080/api/v1',
  socket:'ws',
  chatlist:'chatlist',
  paymentUrl:'checkout',
  freelancerUrl:'freelancer',
  sellerRequest:'sellerrequest',
  dashboard:'dashboard',
  sellerJoin:'join/sellers',
  userJoin:'join/users',
  order:'order',
  job:'job',
  signup:'user',
  user:'user',
  seller:'seller',
  token:'token',
  coupon:'coupon',
  userdashboard:'userdashboard',
  file:'file',
  subscription:'subscription'
};
