export const environment = {
  production: true,
  apiBaseUrl: 'https://api.lawtasks.pro/api/v1',
  socket:'ws',
  chatlist:'chatlist',
  paymentUrl:'checkout',
  freelancerUrl:'freelancer',
  sellerRequest:'sellerrequest',
  dashboard:'dashboard',
  sellerJoin:'join/sellers',
  userJoin:'join/users',
  order:'order',
  job:'job',
  signup:'user',
  user:'user',
  seller:'seller',
  token:'token',
  coupon:'coupon',
  userdashboard:'userdashboard',
  file:'file',
  subscription:'subscription',
  social:'social'
};
