export const environment = {
  production: true,
  stripePublicKey: 'pk_test_51JhGPzEr164QO1Kb8FdmFbmmyAAixxNnftXtvzfwQqun2eToP4OmlZhkjomR9UNiA97TcGuh3IfJsj1BgkLwvcBt00pIFjyExI',
  stripePublicKeyLive:'pk_live_51JhGPzEr164QO1KbD3UXh9LMANe9ItYyBHScGROV4ORdoQ2oiNBvkh7R6FeqtF7KxvZV9n0B2I32eYWwp2q6xEi600mIz5vsuV',
  stripeSecertKey:'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',
  apiBaseUrl: 'http://139.59.215.241/api/v1',
  socket:'ws',
  chatlist:'chatlist',
  paymentUrl:'checkout',
  freelancerUrl:'freelancer',
  sellerRequest:'sellerrequest',
  dashboard:'dashboard',
  sellerJoin:'join/sellers',
  userJoin:'join/users',
  order:'order',
  job:'job',
  signup:'user',
  user:'user',
  seller:'seller',
  token:'token',
  coupon:'coupon',
  userdashboard:'userdashboard',
  file:'file',
  subscription:'subscription',
  social:'social'
};
